// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAtmhvstV1zQ6OU7Dl1BUxQyfi580Fv8',
    appId: '1:868879156399:web:239b3f565ceedaff23405a',
    messagingSenderId: '868879156399',
    projectId: 'fir-memo-app-9298d',
    authDomain: 'fir-memo-app-9298d.firebaseapp.com',
    storageBucket: 'fir-memo-app-9298d.appspot.com',
    measurementId: 'G-PHFSD3P3RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHv0xj1idF565BSDEsM7n1oRYsya1VDsk',
    appId: '1:868879156399:android:9c64b2a280d7599923405a',
    messagingSenderId: '868879156399',
    projectId: 'fir-memo-app-9298d',
    storageBucket: 'fir-memo-app-9298d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzAXyCE4r22WStK7jAEg9awG_xnwUoWTg',
    appId: '1:868879156399:ios:72d1ffff00f577af23405a',
    messagingSenderId: '868879156399',
    projectId: 'fir-memo-app-9298d',
    storageBucket: 'fir-memo-app-9298d.appspot.com',
    iosClientId: '868879156399-qbn4bhkeirhqvrhjjaa74hulme8tvc0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGa4GettingStarted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzAXyCE4r22WStK7jAEg9awG_xnwUoWTg',
    appId: '1:868879156399:ios:544446e8bad7c5db23405a',
    messagingSenderId: '868879156399',
    projectId: 'fir-memo-app-9298d',
    storageBucket: 'fir-memo-app-9298d.appspot.com',
    iosClientId: '868879156399-ei4jvg81d5r33tagkaofujp8lto3qn7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGa4GettingStarted.RunnerTests',
  );
}
